function [labelList,nameList,infoFile]=snslist(areaName,sectionName);
% SNSLIST Menu list for " Signal & System " CAI

% Part I -- Signal Analysis
if strcmp(areaName,'sig_pro'),
   if strcmp(sectionName,'items'),
      labelList=str2mat( ...
         '频谱分析', ...
         '演示实验');
      nameList=str2mat( ...
         'pinpu', ...
         'yanshi');
   elseif strcmp(sectionName(1:4),'pinp'),
      labelList=str2mat( ...
         '连续  周期信号', ...
         '连续非周期信号', ...
         '离散  周期信号', ...
         '离散非周期信号',...
         '实验仿真');
      nameList=str2mat( ...
         'lxzq', ...
         'siga', ...
         'signt', ...
         'sigan',...
         'ppfx');
   elseif strcmp(sectionName(1:4),'yans'),
      labelList=str2mat( ...
         '方波的合成', ...
         '图象的处理', ...
         'DSB 信号');
      nameList=str2mat( ...
         'csshow fsaxz', ...
         'zz1',...
         'sigdwx');
   end
   if nargout==3,
      if strcmp(sectionName(1:4),'yans'),
         infoFile='.\help\help312.txt';
      else
         infoFile='.\help\help311.txt';
      end;
   end;
      
% Part II -- Signal Sampling
elseif strcmp(areaName,'sig_smpl'),
   if strcmp(sectionName,'items'),
      labelList=str2mat( ...
         '连续时间抽样', ...
         '--频谱显示');
      nameList=str2mat( ...
         'Chou_shi', ...
         'cypp');
   end
   if nargout==3,
      infoFile='.\help\help321.txt';
   end;

% Part III -- LTI System Property
elseif strcmp(areaName,'sys_pro'),
   if strcmp(sectionName,'items'),
      labelList=str2mat( ...
         '系统频域特性',...
         '系统时域特性');
      nameList=str2mat( ...
         'pytx',...
         'sytx');
   elseif strcmp(sectionName(1:4),'pytx'), 
      labelList=str2mat( ...
         '一阶RC系统',...
         '二阶RLC系统');
      nameList=str2mat( ...
         'yj', ...
         'rj1');
   elseif strcmp(sectionName(1:4),'sytx'), 
      labelList=str2mat( ...
         '一阶系统的时域特性',...
         '二阶系统的时域特性',...
         '系统的谐振特性');
      nameList=str2mat( ...
         'yjsh', ...
         'rjsh',...
         'xtsh');
   end
   if nargout==3,
      if strcmp(sectionName(1:4),'sytx'),
         infoFile='.\help\help332.txt';
      else
         infoFile='.\help\help331.txt';
      end;
   end;

% Part IV -- System Simulation
elseif strcmp(areaName,'sim_sys'),
   if strcmp(sectionName,'items'),
      labelList=str2mat( ...
         'AM 系统仿真',...
         '实验仿真');
      nameList=str2mat( ...
         'am_sys',...     
         'xhblock');
   end
   if nargout==3,
      infoFile='.\help\help341.txt';
   end;
   
% Part V -- Filter
elseif strcmp(areaName,'sig_flt'),
   if strcmp(sectionName,'items'),
      labelList=str2mat( ...
         '信号滤波举例', ...
         '数字滤波器设计向导', ...
         '查表法设计模拟滤波器');
      nameList=str2mat( ...
         'csshow filtaxz', ...
         'fdshow', ...
         'anflttbl1');
   end
   if nargout==3,
      infoFile='.\help\help351.txt';
   end;

end
