r=[0:1/255:1]';
g=[0:1/255:1]';
b=[0:1/255:1]';
map=[r g b];
hf_2=figure('colormap',map);
set(hf_2,'menubar','none',...
         'name','图像处理系统',...
         'color',[.6 .7 .8],...
         'numbertitle','off')
      axis off
load imdemos
subplot(2,3,4),hi_1=image(flower);axis off
subplot(2,3,5),hi_2=image(pout);axis off
subplot(2,3,6),hi_3=image(trees);axis off
ht_1=text('string','图像源',...
          'unit','centimeter',...
          'position',[-9 7.5],...
          'fontsize',50);
set(hi_1,'buttondownfcn','close,zz2');       
set(hi_2,'buttondownfcn','close,zz3');  
set(hi_3,'buttondownfcn','close,zz4');
hc_2=uicontrol(gcf,'string','返回主页面',...
                   'callback','close',...
                   'position',[440 300 80 30]);
hc_3=uicontrol(gcf,'style','frame',...
                   'position',[420 280 120 80],...
                   'backgroundcolor',[.3 .4 .8]);
ht_1=uicontrol(gcf,'style','text',...
                   'unit','centimeter',... 
                   'position',[4 6.5 4 .5],...
                   'fontsize',15,...
                   'backgroundcolor',[.4 .7 .5],...
                   'string','----选择一幅图像');
                   